In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
import plotly.io as pio
pio.renderers.default='notebook'
import cufflinks as cf

In [3]:
df = pd.read_excel('apr_2020.xlsx')

In [4]:
df.head()

,nama_cabang,apr_total_order,apr_qty_ayam,apr_avg_ayam,apr_total_purchase,q1_total_order,q1_qty_ayam,q1_avg_ayam,q1_total_purchase
0,ACORDION KELAPA GADING,15,300,20.000000,10352000,87,2130,24.482759,70381000
1,AGPG RESTO & CAFE,9,600,66.666667,27095000,78,7575,97.115385,362136800
2,ALAM SUTRA,11,160,14.545455,11444200,69,2245,32.536232,136580300
3,ALUR LAUT,15,300,20.000000,14703000,82,1780,21.707317,73439200
4,AMPERA / (ITC CEMPAKA MAS),11,185,16.818182,6979400,68,1995,29.338235,70595400

#### Menentukan cabang
Dengan Jumlah Order di atas 78 Hari (3 x 26 Hari)

Pada periode Jan-Maret 2020 (Q1)

In [5]:
df[df['q1_total_order']>=78]

,nama_cabang,apr_total_order,apr_qty_ayam,apr_avg_ayam,apr_total_purchase,q1_total_order,q1_qty_ayam,q1_avg_ayam,q1_total_purchase
0,ACORDION KELAPA GADING,15,300,20.000000,10352000,87,2130,24.482759,70381000
1,AGPG RESTO & CAFE,9,600,66.666667,27095000,78,7575,97.115385,362136800
3,ALUR LAUT,15,300,20.000000,14703000,82,1780,21.707317,73439200
6,Andrian / Cipinang,15,320,21.333333,14679100,82,2190,26.707317,94507600
7,ANTILOP - JATICEMPAKA (PONDOK KOPI),13,150,11.538462,5979100,79,1305,16.518987,48898100
...,...,...,...,...,...,...,...,...,...
275,ULUJAMI ( BARU ),12,120,10.000000,3975700,84,1125,13.392857,34633900
278,UNTAR,8,225,28.125000,8867300,80,2990,37.375000,117817900
281,VILLA TAMAN CIBODAS / Prambanan Raya Perum II,15,315,21.000000,11309300,83,2005,24.156627,67697900
282,VILLA TANGERANG INDAH,13,175,13.461538,8309200,80,1605,20.062500,66455400
284,WARUNG JATI - BUNCIT RAYA (SAMSAT CIPUTAT),6,60,10.000000,2593200,82,900,10.975610,32825400

#### Dengan Jumlah cabang sebanyak

In [7]:
df[df['q1_total_order']>=78]['q1_total_order'].count()

133

#### Menentukan Jumlah Cabang yang memiliki Total Order di atas 78 Hari dan Memiliki Rata-rata 30 ekor ke atas

In [8]:
df[(df['q1_total_order']>=78) & (df['q1_avg_ayam']>=30)]

,nama_cabang,apr_total_order,apr_qty_ayam,apr_avg_ayam,apr_total_purchase,q1_total_order,q1_qty_ayam,q1_avg_ayam,q1_total_purchase
1,AGPG RESTO & CAFE,9,600,66.666667,27095000,78,7575,97.115385,362136800
20,BINTARO JAYA SEKTOR 1 (JATI CEMPAKA),13,360,27.692308,15882300,86,3275,38.081395,131292850
22,BINUS ANGGREK,14,840,60.000000,39861600,81,7150,88.271605,318470700
25,BONAGABE - JATINEGARA (BINONG RAYA),13,335,25.769231,12964200,82,2755,33.597561,102545700
31,CEGER,10,410,41.000000,17530600,82,5090,62.073171,236707200
39,CINERE RAYA,15,340,22.666667,19764200,84,2555,30.416667,138102050
44,CIPONDOH MAKMUR,15,870,58.000000,29686000,85,5340,62.823529,177809650
49,CITRA 2,15,330,22.000000,11617800,85,2645,31.117647,91696100
51,CONDET RAYA,10,245,24.500000,12754400,87,2865,32.931034,140234650
65,GRAND DEPOK CITY,15,400,26.666667,19239000,88,3380,38.409091,151868750
67,GREENLAKE,14,350,25.000000,16312700,87,2885,33.160920,131174500
68,GREENVILLE,15,470,31.333333,16018400,79,3720,47.088608,119467400
69,GROGOL,15,465,31.000000,26506800,88,3505,39.829545,161990450
74,HADIAH JELAMBAR,14,565,40.357143,21029900,88,3795,43.125000,135675500
87,JATI WARINGIN,15,365,24.333333,16496500,86,3785,44.011628,149590350
103,Karang Anyar,15,420,28.000000,18025800,88,3540,40.227273,140176500
110,KAYU BESAR BARU,13,335,25.769231,12569100,84,2630,31.309524,96105800
112,KEBAYORAN LAMA,13,360,27.692308,17029000,88,3670,41.704545,148192100
113,KEBON KACANG,15,440,29.333333,19589400,89,4425,49.719101,183671900
121,KEMANGGISAN,10,390,39.000000,16201600,85,5065,59.588235,197698350
122,KEMANGSARI,14,390,27.857143,15908700,83,4505,54.277108,168842900
125,KOLONEL SUGIONO,15,305,20.333333,16291800,80,2940,36.750000,129120450
128,KOSAMBI,15,430,28.666667,17437400,87,2790,32.068966,106112900
130,KOTA BUMI I,15,555,37.000000,21258400,88,3890,44.204545,150224600
138,KREKOT SAMANHUDI,15,615,41.000000,24979000,89,5465,61.404494,216692000
155,MODERNLAND,15,355,23.666667,17742400,88,3070,34.886364,135460700
158,MUARA BAHARI,15,485,32.333333,18764400,89,3685,41.404494,137105500
162,OTISTA RAYA (New),13,410,31.538462,20283100,85,3065,36.058824,130689000
176,PASAR SEGAR BINTARO,14,420,30.000000,14704200,80,3920,49.000000,126491400
180,PEDONGKELAN,11,235,21.363636,7592400,78,2340,30.000000,71048400
188,PENINGGILAN,14,355,25.357143,14790200,83,3145,37.891566,120650000
196,PON PIN KEBAYORAN LAMA,15,790,52.666667,32221200,88,6135,69.715909,236410650
200,PONDOK JAYA,15,425,28.333333,15215400,88,4280,48.636364,140223700
205,POS PENGUMBEN,15,495,33.000000,21726000,83,3740,45.060241,147661000
210,PURI,13,395,30.384615,13099400,84,3430,40.833333,109272800
225,RSUD CENGKARENG,15,375,25.000000,16593400,88,2790,31.704545,117177850
230,SENOPATI,15,375,25.000000,19326700,88,3690,41.931818,190179300
235,SETIA BUDI 2,15,260,17.333333,10923200,89,2865,32.191011,102850900
236,SETIA KAWAN,15,425,28.333333,17425600,87,2740,31.494253,109732900
241,SRENGSENG,13,695,53.461538,35249100,82,5465,66.646341,281110500
256,TANAH MERAH,13,335,25.769231,12655900,82,2560,31.219512,91592100
263,TELUK GONG 1,15,355,23.666667,13475500,87,2765,31.781609,103670400
264,TELUK GONG 2,14,330,23.571429,11400400,81,2725,33.641975,88475800
265,TERAS GANDARIA,15,390,26.000000,15183900,88,3850,43.750000,139496300
266,TERNATE TOMANG,10,335,33.500000,15189400,81,2525,31.172840,116370500
269,TJ DUREN2,15,495,33.000000,19777800,87,2910,33.448276,97803600
278,UNTAR,8,225,28.125000,8867300,80,2990,37.375000,117817900

#### Dengan Jumlah cabang sebanyak

In [9]:
df[(df['q1_total_order']>=78) & (df['q1_avg_ayam']>=30)]['q1_total_order'].count()

47

#### Berapa Total Pembelian masing-masing 47 Cabang tsb dalam periode Jan-Mar 2020?
Dari yang tertinggi ke terendah (Descending)

In [11]:
df[(df['q1_total_order']>=78) & (df['q1_avg_ayam']>=30)][['nama_cabang','q1_total_purchase']].sort_values(by='q1_total_purchase',ascending=False)

                              nama_cabang  q1_total_purchase
1                       AGPG RESTO & CAFE          362136800
22                          BINUS ANGGREK          318470700
241                             SRENGSENG          281110500
31                                  CEGER          236707200
196                PON PIN KEBAYORAN LAMA          236410650
138                      KREKOT SAMANHUDI          216692000
121                           KEMANGGISAN          197698350
230                              SENOPATI          190179300
113                          KEBON KACANG          183671900
44                        CIPONDOH MAKMUR          177809650
122                            KEMANGSARI          168842900
69                                 GROGOL          161990450
65                       GRAND DEPOK CITY          151868750
130                           KOTA BUMI I          150224600
87                          JATI WARINGIN          149590350
112                        KEBAYORAN LAMA          148192100
205                         POS PENGUMBEN          147661000
51                            CONDET RAYA          140234650
200                           PONDOK JAYA          140223700
103                          Karang Anyar          140176500
265                        TERAS GANDARIA          139496300
39                            CINERE RAYA          138102050
158                          MUARA BAHARI          137105500
74                        HADIAH JELAMBAR          135675500
155                            MODERNLAND          135460700
20   BINTARO JAYA SEKTOR 1 (JATI CEMPAKA)          131292850
67                              GREENLAKE          131174500
162                     OTISTA RAYA (New)          130689000
125                       KOLONEL SUGIONO          129120450
176                   PASAR SEGAR BINTARO          126491400
188                           PENINGGILAN          120650000
68                             GREENVILLE          119467400
278                                 UNTAR          117817900
225                       RSUD CENGKARENG          117177850
266                        TERNATE TOMANG          116370500
236                           SETIA KAWAN          109732900
210                                  PURI          109272800
128                               KOSAMBI          106112900
263                          TELUK GONG 1          103670400
235                          SETIA BUDI 2          102850900
25    BONAGABE - JATINEGARA (BINONG RAYA)          102545700
269                             TJ DUREN2           97803600
110                       KAYU BESAR BARU           96105800
49                                CITRA 2           91696100
256                           TANAH MERAH           91592100
264                          TELUK GONG 2           88475800
180                           PEDONGKELAN           71048400

In [12]:
df_47 = df[(df['q1_total_order']>=78) & (df['q1_avg_ayam']>=30)][['nama_cabang','q1_total_purchase']].sort_values(by='q1_total_purchase',ascending=False)

#### Berapa Penjualan Rata-rata cabang tersebut Pada April 2020?

In [13]:
df[(df['q1_total_order']>=78) & (df['q1_avg_ayam']>=30)][['nama_cabang','q1_total_purchase','apr_avg_ayam']].sort_values(by='q1_total_purchase',ascending=False)

                              nama_cabang  q1_total_purchase  apr_avg_ayam
1                       AGPG RESTO & CAFE          362136800     66.666667
22                          BINUS ANGGREK          318470700     60.000000
241                             SRENGSENG          281110500     53.461538
31                                  CEGER          236707200     41.000000
196                PON PIN KEBAYORAN LAMA          236410650     52.666667
138                      KREKOT SAMANHUDI          216692000     41.000000
121                           KEMANGGISAN          197698350     39.000000
230                              SENOPATI          190179300     25.000000
113                          KEBON KACANG          183671900     29.333333
44                        CIPONDOH MAKMUR          177809650     58.000000
122                            KEMANGSARI          168842900     27.857143
69                                 GROGOL          161990450     31.000000
65                       GRAND DEPOK CITY          151868750     26.666667
130                           KOTA BUMI I          150224600     37.000000
87                          JATI WARINGIN          149590350     24.333333
112                        KEBAYORAN LAMA          148192100     27.692308
205                         POS PENGUMBEN          147661000     33.000000
51                            CONDET RAYA          140234650     24.500000
200                           PONDOK JAYA          140223700     28.333333
103                          Karang Anyar          140176500     28.000000
265                        TERAS GANDARIA          139496300     26.000000
39                            CINERE RAYA          138102050     22.666667
158                          MUARA BAHARI          137105500     32.333333
74                        HADIAH JELAMBAR          135675500     40.357143
155                            MODERNLAND          135460700     23.666667
20   BINTARO JAYA SEKTOR 1 (JATI CEMPAKA)          131292850     27.692308
67                              GREENLAKE          131174500     25.000000
162                     OTISTA RAYA (New)          130689000     31.538462
125                       KOLONEL SUGIONO          129120450     20.333333
176                   PASAR SEGAR BINTARO          126491400     30.000000
188                           PENINGGILAN          120650000     25.357143
68                             GREENVILLE          119467400     31.333333
278                                 UNTAR          117817900     28.125000
225                       RSUD CENGKARENG          117177850     25.000000
266                        TERNATE TOMANG          116370500     33.500000
236                           SETIA KAWAN          109732900     28.333333
210                                  PURI          109272800     30.384615
128                               KOSAMBI          106112900     28.666667
263                          TELUK GONG 1          103670400     23.666667
235                          SETIA BUDI 2          102850900     17.333333
25    BONAGABE - JATINEGARA (BINONG RAYA)          102545700     25.769231
269                             TJ DUREN2           97803600     33.000000
110                       KAYU BESAR BARU           96105800     25.769231
49                                CITRA 2           91696100     22.000000
256                           TANAH MERAH           91592100     25.769231
264                          TELUK GONG 2           88475800     23.571429
180                           PEDONGKELAN           71048400     21.363636

#### Berapa Hari cabang tersebut berjualan Pada April 2020?

In [14]:
df[(df['q1_total_order']>=78) & (df['q1_avg_ayam']>=30)][['nama_cabang','q1_total_purchase','apr_avg_ayam','apr_total_order']].sort_values(by='q1_total_purchase',ascending=False)

,nama_cabang,q1_total_purchase,apr_avg_ayam,apr_total_order
1,AGPG RESTO & CAFE,362136800,66.666667,9
22,BINUS ANGGREK,318470700,60.000000,14
241,SRENGSENG,281110500,53.461538,13
31,CEGER,236707200,41.000000,10
196,PON PIN KEBAYORAN LAMA,236410650,52.666667,15
138,KREKOT SAMANHUDI,216692000,41.000000,15
121,KEMANGGISAN,197698350,39.000000,10
230,SENOPATI,190179300,25.000000,15
113,KEBON KACANG,183671900,29.333333,15
44,CIPONDOH MAKMUR,177809650,58.000000,15
122,KEMANGSARI,168842900,27.857143,14
69,GROGOL,161990450,31.000000,15
65,GRAND DEPOK CITY,151868750,26.666667,15
130,KOTA BUMI I,150224600,37.000000,15
87,JATI WARINGIN,149590350,24.333333,15
112,KEBAYORAN LAMA,148192100,27.692308,13
205,POS PENGUMBEN,147661000,33.000000,15
51,CONDET RAYA,140234650,24.500000,10
200,PONDOK JAYA,140223700,28.333333,15
103,Karang Anyar,140176500,28.000000,15
265,TERAS GANDARIA,139496300,26.000000,15
39,CINERE RAYA,138102050,22.666667,15
158,MUARA BAHARI,137105500,32.333333,15
74,HADIAH JELAMBAR,135675500,40.357143,14
155,MODERNLAND,135460700,23.666667,15
20,BINTARO JAYA SEKTOR 1 (JATI CEMPAKA),131292850,27.692308,13
67,GREENLAKE,131174500,25.000000,14
162,OTISTA RAYA (New),130689000,31.538462,13
125,KOLONEL SUGIONO,129120450,20.333333,15
176,PASAR SEGAR BINTARO,126491400,30.000000,14
188,PENINGGILAN,120650000,25.357143,14
68,GREENVILLE,119467400,31.333333,15
278,UNTAR,117817900,28.125000,8
225,RSUD CENGKARENG,117177850,25.000000,15
266,TERNATE TOMANG,116370500,33.500000,10
236,SETIA KAWAN,109732900,28.333333,15
210,PURI,109272800,30.384615,13
128,KOSAMBI,106112900,28.666667,15
263,TELUK GONG 1,103670400,23.666667,15
235,SETIA BUDI 2,102850900,17.333333,15
25,BONAGABE - JATINEGARA (BINONG RAYA),102545700,25.769231,13
269,TJ DUREN2,97803600,33.000000,15
110,KAYU BESAR BARU,96105800,25.769231,13
49,CITRA 2,91696100,22.000000,15
256,TANAH MERAH,91592100,25.769231,13
264,TELUK GONG 2,88475800,23.571429,14
180,PEDONGKELAN,71048400,21.363636,11

#### Bila dibandingkan Q1 (Jan-Maret), apakah ada penurunan/kenaikan?

In [15]:
df[(df['q1_total_order']>=78) & (df['q1_avg_ayam']>=30)][['nama_cabang','q1_total_purchase','apr_avg_ayam','q1_avg_ayam','apr_total_order']]

,nama_cabang,q1_total_purchase,apr_avg_ayam,q1_avg_ayam,apr_total_order
1,AGPG RESTO & CAFE,362136800,66.666667,97.115385,9
20,BINTARO JAYA SEKTOR 1 (JATI CEMPAKA),131292850,27.692308,38.081395,13
22,BINUS ANGGREK,318470700,60.000000,88.271605,14
25,BONAGABE - JATINEGARA (BINONG RAYA),102545700,25.769231,33.597561,13
31,CEGER,236707200,41.000000,62.073171,10
39,CINERE RAYA,138102050,22.666667,30.416667,15
44,CIPONDOH MAKMUR,177809650,58.000000,62.823529,15
49,CITRA 2,91696100,22.000000,31.117647,15
51,CONDET RAYA,140234650,24.500000,32.931034,10
65,GRAND DEPOK CITY,151868750,26.666667,38.409091,15
67,GREENLAKE,131174500,25.000000,33.160920,14
68,GREENVILLE,119467400,31.333333,47.088608,15
69,GROGOL,161990450,31.000000,39.829545,15
74,HADIAH JELAMBAR,135675500,40.357143,43.125000,14
87,JATI WARINGIN,149590350,24.333333,44.011628,15
103,Karang Anyar,140176500,28.000000,40.227273,15
110,KAYU BESAR BARU,96105800,25.769231,31.309524,13
112,KEBAYORAN LAMA,148192100,27.692308,41.704545,13
113,KEBON KACANG,183671900,29.333333,49.719101,15
121,KEMANGGISAN,197698350,39.000000,59.588235,10
122,KEMANGSARI,168842900,27.857143,54.277108,14
125,KOLONEL SUGIONO,129120450,20.333333,36.750000,15
128,KOSAMBI,106112900,28.666667,32.068966,15
130,KOTA BUMI I,150224600,37.000000,44.204545,15
138,KREKOT SAMANHUDI,216692000,41.000000,61.404494,15
155,MODERNLAND,135460700,23.666667,34.886364,15
158,MUARA BAHARI,137105500,32.333333,41.404494,15
162,OTISTA RAYA (New),130689000,31.538462,36.058824,13
176,PASAR SEGAR BINTARO,126491400,30.000000,49.000000,14
180,PEDONGKELAN,71048400,21.363636,30.000000,11
188,PENINGGILAN,120650000,25.357143,37.891566,14
196,PON PIN KEBAYORAN LAMA,236410650,52.666667,69.715909,15
200,PONDOK JAYA,140223700,28.333333,48.636364,15
205,POS PENGUMBEN,147661000,33.000000,45.060241,15
210,PURI,109272800,30.384615,40.833333,13
225,RSUD CENGKARENG,117177850,25.000000,31.704545,15
230,SENOPATI,190179300,25.000000,41.931818,15
235,SETIA BUDI 2,102850900,17.333333,32.191011,15
236,SETIA KAWAN,109732900,28.333333,31.494253,15
241,SRENGSENG,281110500,53.461538,66.646341,13
256,TANAH MERAH,91592100,25.769231,31.219512,13
263,TELUK GONG 1,103670400,23.666667,31.781609,15
264,TELUK GONG 2,88475800,23.571429,33.641975,14
265,TERAS GANDARIA,139496300,26.000000,43.750000,15
266,TERNATE TOMANG,116370500,33.500000,31.172840,10
269,TJ DUREN2,97803600,33.000000,33.448276,15
278,UNTAR,117817900,28.125000,37.375000,8

#### Berapa Persen Penurunan/Kenaikan yang dialami masing-masing cabang berdasarkan rata-rata ayam?

In [16]:
df_47 = df[(df['q1_total_order']>=78) & (df['q1_avg_ayam']>=30)][['nama_cabang','q1_total_purchase','apr_avg_ayam','q1_avg_ayam','apr_total_order']]

In [17]:
df_47['percentage'] = ((df['apr_avg_ayam'] - df['q1_avg_ayam']) / df['q1_avg_ayam'])*100

In [18]:
df_47

,nama_cabang,q1_total_purchase,apr_avg_ayam,q1_avg_ayam,apr_total_order,percentage
1,AGPG RESTO & CAFE,362136800,66.666667,97.115385,9,-31.353135
20,BINTARO JAYA SEKTOR 1 (JATI CEMPAKA),131292850,27.692308,38.081395,13,-27.281268
22,BINUS ANGGREK,318470700,60.000000,88.271605,14,-32.027972
25,BONAGABE - JATINEGARA (BINONG RAYA),102545700,25.769231,33.597561,13,-23.300293
31,CEGER,236707200,41.000000,62.073171,10,-33.948919
39,CINERE RAYA,138102050,22.666667,30.416667,15,-25.479452
44,CIPONDOH MAKMUR,177809650,58.000000,62.823529,15,-7.677903
49,CITRA 2,91696100,22.000000,31.117647,15,-29.300567
51,CONDET RAYA,140234650,24.500000,32.931034,10,-25.602094
65,GRAND DEPOK CITY,151868750,26.666667,38.409091,15,-30.571992
67,GREENLAKE,131174500,25.000000,33.160920,14,-24.610052
68,GREENVILLE,119467400,31.333333,47.088608,15,-33.458781
69,GROGOL,161990450,31.000000,39.829545,15,-22.168331
74,HADIAH JELAMBAR,135675500,40.357143,43.125000,14,-6.418219
87,JATI WARINGIN,149590350,24.333333,44.011628,15,-44.711581
103,Karang Anyar,140176500,28.000000,40.227273,15,-30.395480
110,KAYU BESAR BARU,96105800,25.769231,31.309524,13,-17.695233
112,KEBAYORAN LAMA,148192100,27.692308,41.704545,13,-33.598826
113,KEBON KACANG,183671900,29.333333,49.719101,15,-41.001883
121,KEMANGGISAN,197698350,39.000000,59.588235,10,-34.550839
122,KEMANGSARI,168842900,27.857143,54.277108,14,-48.676074
125,KOLONEL SUGIONO,129120450,20.333333,36.750000,15,-44.671202
128,KOSAMBI,106112900,28.666667,32.068966,15,-10.609319
130,KOTA BUMI I,150224600,37.000000,44.204545,15,-16.298201
138,KREKOT SAMANHUDI,216692000,41.000000,61.404494,15,-33.229643
155,MODERNLAND,135460700,23.666667,34.886364,15,-32.160695
158,MUARA BAHARI,137105500,32.333333,41.404494,15,-21.908639
162,OTISTA RAYA (New),130689000,31.538462,36.058824,13,-12.536077
176,PASAR SEGAR BINTARO,126491400,30.000000,49.000000,14,-38.775510
180,PEDONGKELAN,71048400,21.363636,30.000000,11,-28.787879
188,PENINGGILAN,120650000,25.357143,37.891566,14,-33.079718
196,PON PIN KEBAYORAN LAMA,236410650,52.666667,69.715909,15,-24.455311
200,PONDOK JAYA,140223700,28.333333,48.636364,15,-41.744548
205,POS PENGUMBEN,147661000,33.000000,45.060241,15,-26.764706
210,PURI,109272800,30.384615,40.833333,13,-25.588697
225,RSUD CENGKARENG,117177850,25.000000,31.704545,15,-21.146953
230,SENOPATI,190179300,25.000000,41.931818,15,-40.379404
235,SETIA BUDI 2,102850900,17.333333,32.191011,15,-46.154741
236,SETIA KAWAN,109732900,28.333333,31.494253,15,-10.036496
241,SRENGSENG,281110500,53.461538,66.646341,13,-19.783236
256,TANAH MERAH,91592100,25.769231,31.219512,13,-17.457933
263,TELUK GONG 1,103670400,23.666667,31.781609,15,-25.533454
264,TELUK GONG 2,88475800,23.571429,33.641975,14,-29.934469
265,TERAS GANDARIA,139496300,26.000000,43.750000,15,-40.571429
266,TERNATE TOMANG,116370500,33.500000,31.172840,10,7.465347
269,TJ DUREN2,97803600,33.000000,33.448276,15,-1.340206
278,UNTAR,117817900,28.125000,37.375000,8,-24.749164

#### Siapa yang paling layak diberikan stimulus?

Dengan penurunan paling kecil ke penurunan paling besar

##### Cabang dengan penurunan terkecil atau bahkan mengalami kenaikan, menjadi prioritas penerima stimulus

In [20]:
df_47 = df_47.sort_values(by='percentage',ascending=False)
df_47

,nama_cabang,q1_total_purchase,apr_avg_ayam,q1_avg_ayam,apr_total_order,percentage
266,TERNATE TOMANG,116370500,33.500000,31.172840,10,7.465347
269,TJ DUREN2,97803600,33.000000,33.448276,15,-1.340206
74,HADIAH JELAMBAR,135675500,40.357143,43.125000,14,-6.418219
44,CIPONDOH MAKMUR,177809650,58.000000,62.823529,15,-7.677903
236,SETIA KAWAN,109732900,28.333333,31.494253,15,-10.036496
128,KOSAMBI,106112900,28.666667,32.068966,15,-10.609319
162,OTISTA RAYA (New),130689000,31.538462,36.058824,13,-12.536077
130,KOTA BUMI I,150224600,37.000000,44.204545,15,-16.298201
256,TANAH MERAH,91592100,25.769231,31.219512,13,-17.457933
110,KAYU BESAR BARU,96105800,25.769231,31.309524,13,-17.695233
241,SRENGSENG,281110500,53.461538,66.646341,13,-19.783236
225,RSUD CENGKARENG,117177850,25.000000,31.704545,15,-21.146953
158,MUARA BAHARI,137105500,32.333333,41.404494,15,-21.908639
69,GROGOL,161990450,31.000000,39.829545,15,-22.168331
25,BONAGABE - JATINEGARA (BINONG RAYA),102545700,25.769231,33.597561,13,-23.300293
196,PON PIN KEBAYORAN LAMA,236410650,52.666667,69.715909,15,-24.455311
67,GREENLAKE,131174500,25.000000,33.160920,14,-24.610052
278,UNTAR,117817900,28.125000,37.375000,8,-24.749164
39,CINERE RAYA,138102050,22.666667,30.416667,15,-25.479452
263,TELUK GONG 1,103670400,23.666667,31.781609,15,-25.533454
210,PURI,109272800,30.384615,40.833333,13,-25.588697
51,CONDET RAYA,140234650,24.500000,32.931034,10,-25.602094
205,POS PENGUMBEN,147661000,33.000000,45.060241,15,-26.764706
20,BINTARO JAYA SEKTOR 1 (JATI CEMPAKA),131292850,27.692308,38.081395,13,-27.281268
180,PEDONGKELAN,71048400,21.363636,30.000000,11,-28.787879
49,CITRA 2,91696100,22.000000,31.117647,15,-29.300567
264,TELUK GONG 2,88475800,23.571429,33.641975,14,-29.934469
103,Karang Anyar,140176500,28.000000,40.227273,15,-30.395480
65,GRAND DEPOK CITY,151868750,26.666667,38.409091,15,-30.571992
1,AGPG RESTO & CAFE,362136800,66.666667,97.115385,9,-31.353135
22,BINUS ANGGREK,318470700,60.000000,88.271605,14,-32.027972
155,MODERNLAND,135460700,23.666667,34.886364,15,-32.160695
188,PENINGGILAN,120650000,25.357143,37.891566,14,-33.079718
138,KREKOT SAMANHUDI,216692000,41.000000,61.404494,15,-33.229643
68,GREENVILLE,119467400,31.333333,47.088608,15,-33.458781
112,KEBAYORAN LAMA,148192100,27.692308,41.704545,13,-33.598826
31,CEGER,236707200,41.000000,62.073171,10,-33.948919
121,KEMANGGISAN,197698350,39.000000,59.588235,10,-34.550839
176,PASAR SEGAR BINTARO,126491400,30.000000,49.000000,14,-38.775510
230,SENOPATI,190179300,25.000000,41.931818,15,-40.379404
265,TERAS GANDARIA,139496300,26.000000,43.750000,15,-40.571429
113,KEBON KACANG,183671900,29.333333,49.719101,15,-41.001883
200,PONDOK JAYA,140223700,28.333333,48.636364,15,-41.744548
125,KOLONEL SUGIONO,129120450,20.333333,36.750000,15,-44.671202
87,JATI WARINGIN,149590350,24.333333,44.011628,15,-44.711581
235,SETIA BUDI 2,102850900,17.333333,32.191011,15,-46.154741
122,KEMANGSARI,168842900,27.857143,54.277108,14,-48.676074

#### Berapa Gross Margin yang didapat dari Cabang tersebut pada Q1 (Jan-Mar)?
Bila HPP = 80%

In [21]:
df_47['gross_margin'] = df_47['q1_total_purchase']* 0.2

In [22]:
df_47

,nama_cabang,q1_total_purchase,apr_avg_ayam,q1_avg_ayam,apr_total_order,percentage,gross_margin
266,TERNATE TOMANG,116370500,33.500000,31.172840,10,7.465347,23274100.0
269,TJ DUREN2,97803600,33.000000,33.448276,15,-1.340206,19560720.0
74,HADIAH JELAMBAR,135675500,40.357143,43.125000,14,-6.418219,27135100.0
44,CIPONDOH MAKMUR,177809650,58.000000,62.823529,15,-7.677903,35561930.0
236,SETIA KAWAN,109732900,28.333333,31.494253,15,-10.036496,21946580.0
128,KOSAMBI,106112900,28.666667,32.068966,15,-10.609319,21222580.0
162,OTISTA RAYA (New),130689000,31.538462,36.058824,13,-12.536077,26137800.0
130,KOTA BUMI I,150224600,37.000000,44.204545,15,-16.298201,30044920.0
256,TANAH MERAH,91592100,25.769231,31.219512,13,-17.457933,18318420.0
110,KAYU BESAR BARU,96105800,25.769231,31.309524,13,-17.695233,19221160.0
241,SRENGSENG,281110500,53.461538,66.646341,13,-19.783236,56222100.0
225,RSUD CENGKARENG,117177850,25.000000,31.704545,15,-21.146953,23435570.0
158,MUARA BAHARI,137105500,32.333333,41.404494,15,-21.908639,27421100.0
69,GROGOL,161990450,31.000000,39.829545,15,-22.168331,32398090.0
25,BONAGABE - JATINEGARA (BINONG RAYA),102545700,25.769231,33.597561,13,-23.300293,20509140.0
196,PON PIN KEBAYORAN LAMA,236410650,52.666667,69.715909,15,-24.455311,47282130.0
67,GREENLAKE,131174500,25.000000,33.160920,14,-24.610052,26234900.0
278,UNTAR,117817900,28.125000,37.375000,8,-24.749164,23563580.0
39,CINERE RAYA,138102050,22.666667,30.416667,15,-25.479452,27620410.0
263,TELUK GONG 1,103670400,23.666667,31.781609,15,-25.533454,20734080.0
210,PURI,109272800,30.384615,40.833333,13,-25.588697,21854560.0
51,CONDET RAYA,140234650,24.500000,32.931034,10,-25.602094,28046930.0
205,POS PENGUMBEN,147661000,33.000000,45.060241,15,-26.764706,29532200.0
20,BINTARO JAYA SEKTOR 1 (JATI CEMPAKA),131292850,27.692308,38.081395,13,-27.281268,26258570.0
180,PEDONGKELAN,71048400,21.363636,30.000000,11,-28.787879,14209680.0
49,CITRA 2,91696100,22.000000,31.117647,15,-29.300567,18339220.0
264,TELUK GONG 2,88475800,23.571429,33.641975,14,-29.934469,17695160.0
103,Karang Anyar,140176500,28.000000,40.227273,15,-30.395480,28035300.0
65,GRAND DEPOK CITY,151868750,26.666667,38.409091,15,-30.571992,30373750.0
1,AGPG RESTO & CAFE,362136800,66.666667,97.115385,9,-31.353135,72427360.0
22,BINUS ANGGREK,318470700,60.000000,88.271605,14,-32.027972,63694140.0
155,MODERNLAND,135460700,23.666667,34.886364,15,-32.160695,27092140.0
188,PENINGGILAN,120650000,25.357143,37.891566,14,-33.079718,24130000.0
138,KREKOT SAMANHUDI,216692000,41.000000,61.404494,15,-33.229643,43338400.0
68,GREENVILLE,119467400,31.333333,47.088608,15,-33.458781,23893480.0
112,KEBAYORAN LAMA,148192100,27.692308,41.704545,13,-33.598826,29638420.0
31,CEGER,236707200,41.000000,62.073171,10,-33.948919,47341440.0
121,KEMANGGISAN,197698350,39.000000,59.588235,10,-34.550839,39539670.0
176,PASAR SEGAR BINTARO,126491400,30.000000,49.000000,14,-38.775510,25298280.0
230,SENOPATI,190179300,25.000000,41.931818,15,-40.379404,38035860.0
265,TERAS GANDARIA,139496300,26.000000,43.750000,15,-40.571429,27899260.0
113,KEBON KACANG,183671900,29.333333,49.719101,15,-41.001883,36734380.0
200,PONDOK JAYA,140223700,28.333333,48.636364,15,-41.744548,28044740.0
125,KOLONEL SUGIONO,129120450,20.333333,36.750000,15,-44.671202,25824090.0
87,JATI WARINGIN,149590350,24.333333,44.011628,15,-44.711581,29918070.0
235,SETIA BUDI 2,102850900,17.333333,32.191011,15,-46.154741,20570180.0
122,KEMANGSARI,168842900,27.857143,54.277108,14,-48.676074,33768580.0

#### Berapa Rata-rata Gross Margin yang didapat dari cabang-cabang tesebut?

##### Sebagai acuan jumlah maksimal stimulus selama 3 bulan yang akan diterima cabang

In [23]:
df_47['gross_margin'].mean()

29774005.74468085

#### Maximum to Minimum  gross margin

In [60]:
df_47.sort_values(by='gross_margin',ascending=False)

,nama_cabang,q1_total_purchase,apr_avg_ayam,q1_avg_ayam,apr_total_order,percentage,gross_margin
1,AGPG RESTO & CAFE,362136800,66.666667,97.115385,9,-31.353135,72427360.0
22,BINUS ANGGREK,318470700,60.000000,88.271605,14,-32.027972,63694140.0
241,SRENGSENG,281110500,53.461538,66.646341,13,-19.783236,56222100.0
31,CEGER,236707200,41.000000,62.073171,10,-33.948919,47341440.0
196,PON PIN KEBAYORAN LAMA,236410650,52.666667,69.715909,15,-24.455311,47282130.0
138,KREKOT SAMANHUDI,216692000,41.000000,61.404494,15,-33.229643,43338400.0
121,KEMANGGISAN,197698350,39.000000,59.588235,10,-34.550839,39539670.0
230,SENOPATI,190179300,25.000000,41.931818,15,-40.379404,38035860.0
113,KEBON KACANG,183671900,29.333333,49.719101,15,-41.001883,36734380.0
44,CIPONDOH MAKMUR,177809650,58.000000,62.823529,15,-7.677903,35561930.0
122,KEMANGSARI,168842900,27.857143,54.277108,14,-48.676074,33768580.0
69,GROGOL,161990450,31.000000,39.829545,15,-22.168331,32398090.0
65,GRAND DEPOK CITY,151868750,26.666667,38.409091,15,-30.571992,30373750.0
130,KOTA BUMI I,150224600,37.000000,44.204545,15,-16.298201,30044920.0
87,JATI WARINGIN,149590350,24.333333,44.011628,15,-44.711581,29918070.0
112,KEBAYORAN LAMA,148192100,27.692308,41.704545,13,-33.598826,29638420.0
205,POS PENGUMBEN,147661000,33.000000,45.060241,15,-26.764706,29532200.0
51,CONDET RAYA,140234650,24.500000,32.931034,10,-25.602094,28046930.0
200,PONDOK JAYA,140223700,28.333333,48.636364,15,-41.744548,28044740.0
103,Karang Anyar,140176500,28.000000,40.227273,15,-30.395480,28035300.0
265,TERAS GANDARIA,139496300,26.000000,43.750000,15,-40.571429,27899260.0
39,CINERE RAYA,138102050,22.666667,30.416667,15,-25.479452,27620410.0
158,MUARA BAHARI,137105500,32.333333,41.404494,15,-21.908639,27421100.0
74,HADIAH JELAMBAR,135675500,40.357143,43.125000,14,-6.418219,27135100.0
155,MODERNLAND,135460700,23.666667,34.886364,15,-32.160695,27092140.0
20,BINTARO JAYA SEKTOR 1 (JATI CEMPAKA),131292850,27.692308,38.081395,13,-27.281268,26258570.0
67,GREENLAKE,131174500,25.000000,33.160920,14,-24.610052,26234900.0
162,OTISTA RAYA (New),130689000,31.538462,36.058824,13,-12.536077,26137800.0
125,KOLONEL SUGIONO,129120450,20.333333,36.750000,15,-44.671202,25824090.0
176,PASAR SEGAR BINTARO,126491400,30.000000,49.000000,14,-38.775510,25298280.0
188,PENINGGILAN,120650000,25.357143,37.891566,14,-33.079718,24130000.0
68,GREENVILLE,119467400,31.333333,47.088608,15,-33.458781,23893480.0
278,UNTAR,117817900,28.125000,37.375000,8,-24.749164,23563580.0
225,RSUD CENGKARENG,117177850,25.000000,31.704545,15,-21.146953,23435570.0
266,TERNATE TOMANG,116370500,33.500000,31.172840,10,7.465347,23274100.0
236,SETIA KAWAN,109732900,28.333333,31.494253,15,-10.036496,21946580.0
210,PURI,109272800,30.384615,40.833333,13,-25.588697,21854560.0
128,KOSAMBI,106112900,28.666667,32.068966,15,-10.609319,21222580.0
263,TELUK GONG 1,103670400,23.666667,31.781609,15,-25.533454,20734080.0
235,SETIA BUDI 2,102850900,17.333333,32.191011,15,-46.154741,20570180.0
25,BONAGABE - JATINEGARA (BINONG RAYA),102545700,25.769231,33.597561,13,-23.300293,20509140.0
269,TJ DUREN2,97803600,33.000000,33.448276,15,-1.340206,19560720.0
110,KAYU BESAR BARU,96105800,25.769231,31.309524,13,-17.695233,19221160.0
49,CITRA 2,91696100,22.000000,31.117647,15,-29.300567,18339220.0
256,TANAH MERAH,91592100,25.769231,31.219512,13,-17.457933,18318420.0
264,TELUK GONG 2,88475800,23.571429,33.641975,14,-29.934469,17695160.0
180,PEDONGKELAN,71048400,21.363636,30.000000,11,-28.787879,14209680.0

In [65]:
def label_owner (row):
       if row['nama_cabang'] == 'AGPG RESTO & CAFE' :
          return 'Internal'
       if row['nama_cabang'] == 'SRENGSENG' :
          return 'Internal'
       if row['nama_cabang'] == 'KEMANGGISAN' :
          return 'Internal'
       if row['nama_cabang'] == 'CIPONDOH MAKMUR':
          return 'Internal'
       if row['nama_cabang']  == 'GROGOL':
          return 'Internal'
       if row['nama_cabang'] == 'PURI':
          return 'Internal'
       if row['nama_cabang'] == 'SETIA BUDI 2':
          return 'Internal'
       if row['nama_cabang'] == 'TJ DUREN2':
        return 'Internal'
       return 'Eksternal'

In [67]:
df_47.apply(lambda row: label_owner(row), axis=1)

266    Eksternal
269     Internal
74     Eksternal
44      Internal
236    Eksternal
128    Eksternal
162    Eksternal
130    Eksternal
256    Eksternal
110    Eksternal
241     Internal
225    Eksternal
158    Eksternal
69      Internal
25     Eksternal
196    Eksternal
67     Eksternal
278    Eksternal
39     Eksternal
263    Eksternal
210     Internal
51     Eksternal
205    Eksternal
20     Eksternal
180    Eksternal
49     Eksternal
264    Eksternal
103    Eksternal
65     Eksternal
1       Internal
22     Eksternal
155    Eksternal
188    Eksternal
138    Eksternal
68     Eksternal
112    Eksternal
31     Eksternal
121     Internal
176    Eksternal
230    Eksternal
265    Eksternal
113    Eksternal
200    Eksternal
125    Eksternal
87     Eksternal
235     Internal
122    Eksternal
dtype: object

In [68]:
df_47['owner_label'] = df_47.apply (lambda row: label_owner(row), axis=1)

In [71]:
df_47 = df_47.sort_values(by='percentage',ascending=False)
df_47

,nama_cabang,q1_total_purchase,apr_avg_ayam,q1_avg_ayam,apr_total_order,percentage,gross_margin,owner_label
266,TERNATE TOMANG,116370500,33.500000,31.172840,10,7.465347,23274100.0,Eksternal
269,TJ DUREN2,97803600,33.000000,33.448276,15,-1.340206,19560720.0,Internal
74,HADIAH JELAMBAR,135675500,40.357143,43.125000,14,-6.418219,27135100.0,Eksternal
44,CIPONDOH MAKMUR,177809650,58.000000,62.823529,15,-7.677903,35561930.0,Internal
236,SETIA KAWAN,109732900,28.333333,31.494253,15,-10.036496,21946580.0,Eksternal
128,KOSAMBI,106112900,28.666667,32.068966,15,-10.609319,21222580.0,Eksternal
162,OTISTA RAYA (New),130689000,31.538462,36.058824,13,-12.536077,26137800.0,Eksternal
130,KOTA BUMI I,150224600,37.000000,44.204545,15,-16.298201,30044920.0,Eksternal
256,TANAH MERAH,91592100,25.769231,31.219512,13,-17.457933,18318420.0,Eksternal
110,KAYU BESAR BARU,96105800,25.769231,31.309524,13,-17.695233,19221160.0,Eksternal
241,SRENGSENG,281110500,53.461538,66.646341,13,-19.783236,56222100.0,Internal
225,RSUD CENGKARENG,117177850,25.000000,31.704545,15,-21.146953,23435570.0,Eksternal
158,MUARA BAHARI,137105500,32.333333,41.404494,15,-21.908639,27421100.0,Eksternal
69,GROGOL,161990450,31.000000,39.829545,15,-22.168331,32398090.0,Internal
25,BONAGABE - JATINEGARA (BINONG RAYA),102545700,25.769231,33.597561,13,-23.300293,20509140.0,Eksternal
196,PON PIN KEBAYORAN LAMA,236410650,52.666667,69.715909,15,-24.455311,47282130.0,Eksternal
67,GREENLAKE,131174500,25.000000,33.160920,14,-24.610052,26234900.0,Eksternal
278,UNTAR,117817900,28.125000,37.375000,8,-24.749164,23563580.0,Eksternal
39,CINERE RAYA,138102050,22.666667,30.416667,15,-25.479452,27620410.0,Eksternal
263,TELUK GONG 1,103670400,23.666667,31.781609,15,-25.533454,20734080.0,Eksternal
210,PURI,109272800,30.384615,40.833333,13,-25.588697,21854560.0,Internal
51,CONDET RAYA,140234650,24.500000,32.931034,10,-25.602094,28046930.0,Eksternal
205,POS PENGUMBEN,147661000,33.000000,45.060241,15,-26.764706,29532200.0,Eksternal
20,BINTARO JAYA SEKTOR 1 (JATI CEMPAKA),131292850,27.692308,38.081395,13,-27.281268,26258570.0,Eksternal
180,PEDONGKELAN,71048400,21.363636,30.000000,11,-28.787879,14209680.0,Eksternal
49,CITRA 2,91696100,22.000000,31.117647,15,-29.300567,18339220.0,Eksternal
264,TELUK GONG 2,88475800,23.571429,33.641975,14,-29.934469,17695160.0,Eksternal
103,Karang Anyar,140176500,28.000000,40.227273,15,-30.395480,28035300.0,Eksternal
65,GRAND DEPOK CITY,151868750,26.666667,38.409091,15,-30.571992,30373750.0,Eksternal
1,AGPG RESTO & CAFE,362136800,66.666667,97.115385,9,-31.353135,72427360.0,Internal
22,BINUS ANGGREK,318470700,60.000000,88.271605,14,-32.027972,63694140.0,Eksternal
155,MODERNLAND,135460700,23.666667,34.886364,15,-32.160695,27092140.0,Eksternal
188,PENINGGILAN,120650000,25.357143,37.891566,14,-33.079718,24130000.0,Eksternal
138,KREKOT SAMANHUDI,216692000,41.000000,61.404494,15,-33.229643,43338400.0,Eksternal
68,GREENVILLE,119467400,31.333333,47.088608,15,-33.458781,23893480.0,Eksternal
112,KEBAYORAN LAMA,148192100,27.692308,41.704545,13,-33.598826,29638420.0,Eksternal
31,CEGER,236707200,41.000000,62.073171,10,-33.948919,47341440.0,Eksternal
121,KEMANGGISAN,197698350,39.000000,59.588235,10,-34.550839,39539670.0,Internal
176,PASAR SEGAR BINTARO,126491400,30.000000,49.000000,14,-38.775510,25298280.0,Eksternal
230,SENOPATI,190179300,25.000000,41.931818,15,-40.379404,38035860.0,Eksternal
265,TERAS GANDARIA,139496300,26.000000,43.750000,15,-40.571429,27899260.0,Eksternal
113,KEBON KACANG,183671900,29.333333,49.719101,15,-41.001883,36734380.0,Eksternal
200,PONDOK JAYA,140223700,28.333333,48.636364,15,-41.744548,28044740.0,Eksternal
125,KOLONEL SUGIONO,129120450,20.333333,36.750000,15,-44.671202,25824090.0,Eksternal
87,JATI WARINGIN,149590350,24.333333,44.011628,15,-44.711581,29918070.0,Eksternal
235,SETIA BUDI 2,102850900,17.333333,32.191011,15,-46.154741,20570180.0,Internal
122,KEMANGSARI,168842900,27.857143,54.277108,14,-48.676074,33768580.0,Eksternal

#### External Only

In [72]:
df_47[df_47['owner_label'] == 'Eksternal']

,nama_cabang,q1_total_purchase,apr_avg_ayam,q1_avg_ayam,apr_total_order,percentage,gross_margin,owner_label
266,TERNATE TOMANG,116370500,33.500000,31.172840,10,7.465347,23274100.0,Eksternal
74,HADIAH JELAMBAR,135675500,40.357143,43.125000,14,-6.418219,27135100.0,Eksternal
236,SETIA KAWAN,109732900,28.333333,31.494253,15,-10.036496,21946580.0,Eksternal
128,KOSAMBI,106112900,28.666667,32.068966,15,-10.609319,21222580.0,Eksternal
162,OTISTA RAYA (New),130689000,31.538462,36.058824,13,-12.536077,26137800.0,Eksternal
130,KOTA BUMI I,150224600,37.000000,44.204545,15,-16.298201,30044920.0,Eksternal
256,TANAH MERAH,91592100,25.769231,31.219512,13,-17.457933,18318420.0,Eksternal
110,KAYU BESAR BARU,96105800,25.769231,31.309524,13,-17.695233,19221160.0,Eksternal
225,RSUD CENGKARENG,117177850,25.000000,31.704545,15,-21.146953,23435570.0,Eksternal
158,MUARA BAHARI,137105500,32.333333,41.404494,15,-21.908639,27421100.0,Eksternal
25,BONAGABE - JATINEGARA (BINONG RAYA),102545700,25.769231,33.597561,13,-23.300293,20509140.0,Eksternal
196,PON PIN KEBAYORAN LAMA,236410650,52.666667,69.715909,15,-24.455311,47282130.0,Eksternal
67,GREENLAKE,131174500,25.000000,33.160920,14,-24.610052,26234900.0,Eksternal
278,UNTAR,117817900,28.125000,37.375000,8,-24.749164,23563580.0,Eksternal
39,CINERE RAYA,138102050,22.666667,30.416667,15,-25.479452,27620410.0,Eksternal
263,TELUK GONG 1,103670400,23.666667,31.781609,15,-25.533454,20734080.0,Eksternal
51,CONDET RAYA,140234650,24.500000,32.931034,10,-25.602094,28046930.0,Eksternal
205,POS PENGUMBEN,147661000,33.000000,45.060241,15,-26.764706,29532200.0,Eksternal
20,BINTARO JAYA SEKTOR 1 (JATI CEMPAKA),131292850,27.692308,38.081395,13,-27.281268,26258570.0,Eksternal
180,PEDONGKELAN,71048400,21.363636,30.000000,11,-28.787879,14209680.0,Eksternal
49,CITRA 2,91696100,22.000000,31.117647,15,-29.300567,18339220.0,Eksternal
264,TELUK GONG 2,88475800,23.571429,33.641975,14,-29.934469,17695160.0,Eksternal
103,Karang Anyar,140176500,28.000000,40.227273,15,-30.395480,28035300.0,Eksternal
65,GRAND DEPOK CITY,151868750,26.666667,38.409091,15,-30.571992,30373750.0,Eksternal
22,BINUS ANGGREK,318470700,60.000000,88.271605,14,-32.027972,63694140.0,Eksternal
155,MODERNLAND,135460700,23.666667,34.886364,15,-32.160695,27092140.0,Eksternal
188,PENINGGILAN,120650000,25.357143,37.891566,14,-33.079718,24130000.0,Eksternal
138,KREKOT SAMANHUDI,216692000,41.000000,61.404494,15,-33.229643,43338400.0,Eksternal
68,GREENVILLE,119467400,31.333333,47.088608,15,-33.458781,23893480.0,Eksternal
112,KEBAYORAN LAMA,148192100,27.692308,41.704545,13,-33.598826,29638420.0,Eksternal
31,CEGER,236707200,41.000000,62.073171,10,-33.948919,47341440.0,Eksternal
176,PASAR SEGAR BINTARO,126491400,30.000000,49.000000,14,-38.775510,25298280.0,Eksternal
230,SENOPATI,190179300,25.000000,41.931818,15,-40.379404,38035860.0,Eksternal
265,TERAS GANDARIA,139496300,26.000000,43.750000,15,-40.571429,27899260.0,Eksternal
113,KEBON KACANG,183671900,29.333333,49.719101,15,-41.001883,36734380.0,Eksternal
200,PONDOK JAYA,140223700,28.333333,48.636364,15,-41.744548,28044740.0,Eksternal
125,KOLONEL SUGIONO,129120450,20.333333,36.750000,15,-44.671202,25824090.0,Eksternal
87,JATI WARINGIN,149590350,24.333333,44.011628,15,-44.711581,29918070.0,Eksternal
122,KEMANGSARI,168842900,27.857143,54.277108,14,-48.676074,33768580.0,Eksternal

#### Internal Only

In [73]:
df_47[df_47['owner_label'] == 'Internal']

,nama_cabang,q1_total_purchase,apr_avg_ayam,q1_avg_ayam,apr_total_order,percentage,gross_margin,owner_label
269,TJ DUREN2,97803600,33.000000,33.448276,15,-1.340206,19560720.0,Internal
44,CIPONDOH MAKMUR,177809650,58.000000,62.823529,15,-7.677903,35561930.0,Internal
241,SRENGSENG,281110500,53.461538,66.646341,13,-19.783236,56222100.0,Internal
69,GROGOL,161990450,31.000000,39.829545,15,-22.168331,32398090.0,Internal
210,PURI,109272800,30.384615,40.833333,13,-25.588697,21854560.0,Internal
1,AGPG RESTO & CAFE,362136800,66.666667,97.115385,9,-31.353135,72427360.0,Internal
121,KEMANGGISAN,197698350,39.000000,59.588235,10,-34.550839,39539670.0,Internal
235,SETIA BUDI 2,102850900,17.333333,32.191011,15,-46.154741,20570180.0,Internal